### ISSUE TITLE
Rails group capstone: set up your Kanban board 

### ISSUE THREAD

**Issue by zewdu444** [mp-learning-journey/recipe_app#11]
## Rails group capstone: set up your Kanban board 
In this milestone we have prepared Kanban board in a group of two.
here is a link for the project https://github.com/mrprotocoll/recipe_app/projects/1

here are a team members

1. @mrprotocoll   (Team member 1)
2. @zewdu444  (Team member 2)

**Comment by TuyishimireEric** [comment]
# Status: APPROVED 🟢  
### Hi  @TEAM 👋 👋 

#### I'm @TuyishimireEric, Your code reviewer,
Good job on implementing the project requirements! 🥇 
![done](https://media.giphy.com/media/l1uga8ObPBnIBoXUQ/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it 🦾  
Congratulations! 🎉

## Highlights
✔ Descriptive tasks👍
✔ Tasks are distributed in a fair way. 👍
### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/enus/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
